### ISSUE TITLE
[REQ] Improvements to the marked discord group

### ISSUE THREAD

**Issue by crashzk** [wiruwiru/NeedSystem-CS2#1]
![image](https://github.com/user-attachments/assets/14a3044e-732b-4bcf-a04a-76cdfeb5ad6a)

In this case, I configured the message, but I did not select any discord group. As you can see in the printout, the @ was still automatically.

Any way to make sure that if you don't select any discord group, it won't send it, just the message.

**Comment by wiruwiru** [comment]
I will try to fix it in a next update. Maybe making it possible to disable and enable this message, or simply if the MentionRoleID option is null not to show <@&>.

**Comment by wiruwiru** [comment]
Added in [NeedSystem v1.0.6](https://github.com/wiruwiru/NeedSystem-CS2/releases/tag/build-17). 
Thanks for the suggestion!
