### ISSUE TITLE
[REQ] Aliases ​​commands

### ISSUE THREAD

**Issue by crashzk** [wiruwiru/NeedSystem-CS2#2]
Would it be possible to also implement aliases commands?

I would like to configure, in addition to the standard CSSharp commands `css_need`, `!need` and `/need`, I would like to configure the `.need` command so that when the player uses it with `.` it would work too.

**Comment by wiruwiru** [comment]
You can add that from CS# core.json in the second line of the configuration “PublicChatTrigger”: [ “!”, “.” ]

**Comment by crashzk** [comment]
Yes, for now I am using this alternative. I don't want to leave all commands with . also, just need.

**Comment by wiruwiru** [comment]
I'll see what I can do, I'm still going to prioritize the other suggestions before trying this.

**Comment by wiruwiru** [comment]
Added in [NeedSystem v1.0.8](https://github.com/wiruwiru/NeedSystem-CS2/releases/tag/build-20). 
Thanks for the suggestion!
