### ISSUE TITLE
[REQ] Show player nicknames in webhook

### ISSUE THREAD

**Issue by crashzk** [wiruwiru/NeedSystem-CS2#3]
![image](https://github.com/user-attachments/assets/82375697-2bf0-42ba-9fa4-8e6b2e75061f)

Would it be possible to show the players' nicknames instead of the total number of players?

Show the team he is on and the name of the players on the team.

**Comment by crashzk** [comment]
I believe it would be interesting if the player's nickname was also a link to open their Steam profile.

**Comment by wiruwiru** [comment]
I will try to add it in a next update, it is a good idea.

**Comment by wiruwiru** [comment]
Added in [NeedSystem v1.0.7](https://github.com/wiruwiru/NeedSystem-CS2/releases/tag/build-18). 
![image](https://github.com/user-attachments/assets/66126ccc-daa8-4991-863b-5bb3c3444621)

Thanks for the suggestion!
