### ISSUE TITLE
[REQ] Show map image in webhook

### ISSUE THREAD

**Issue by crashzk** [wiruwiru/NeedSystem-CS2#4]
![image](https://github.com/user-attachments/assets/f3a01b7f-9fb4-488b-850b-bf05fab39e2b)

Would something like that be possible? Podemos pegar os mapas do GameTracker mesmo.

https://image.gametracker.com/images/maps/160x120/csgo/de_mirage.jpg

**Comment by wiruwiru** [comment]
That's a good idea, I will try to add it in the next update. I think in a configuration option to enable or disable this function and another option to set a url where to get the images so administrators can upload their own images.

**Comment by wiruwiru** [comment]
Added in [NeedSystem v1.0.6](https://github.com/wiruwiru/NeedSystem-CS2/releases/tag/build-17). 
Thanks for the suggestion!
