### ISSUE TITLE
[REQ] Automatically detect server IP

### ISSUE THREAD

**Issue by crashzk** [wiruwiru/NeedSystem-CS2#6]
Any way to make the plugin automatically detect the server's IP? I ask because it takes some work to configure server IP and port per server in their configurations.
```
// This configuration was automatically generated by CounterStrikeSharp for plugin 'NeedSystem', at 2024/10/18 06:46:35
{
  "WebhookUrl": "https://discord.com/api/webhooks/",
  "IPandPORT": "",
  "CustomDomain": "",
  "MentionRoleID": "",
  "MaxServerPlayers": 12,
  "MinPlayers": 10,
  "CommandCooldownSeconds": 300,
  "Command": [
    "css_need",
    ".need",
	"css_complete",
	".complete"
  ],
  "EmbedImage": true,
  "EmbedColor": "#ffb800",
  "ImagesURL": "https://imagenes.redage.es/CS2/{map}.png",
  "PlayerNameList": true,
  "EmbedFooter": true,
  "EmbedFooterImage": "",
  "EmbedAuthor": true,
  "EmbedAuthorURL": "",
  "EmbedAuthorImage": "",
  "ConfigVersion": 1
}
```

**Comment by wiruwiru** [comment]
I don't know any method to get ip:port and set it automatically in the configuration, I will check in the community and if I can find out how to do it I will implement it when I can.

**Comment by wiruwiru** [comment]
Added in [NeedSystem v1.1.2](https://github.com/wiruwiru/NeedSystem-CS2/releases/tag/build-26). 
Thanks for the suggestion!
