### ISSUE TITLE
[REQ] Support `thumbnail` for webhook

### ISSUE THREAD

**Issue by crashzk** [wiruwiru/NeedSystem-CS2#7]
Would it be possible to add support for `thumbnail` to the discord webhook?

It would send an image that we configure along with the webhook message.

![image](https://github.com/user-attachments/assets/c7cfb35c-fe75-446e-a6d7-14a0896b203e)

**Comment by wiruwiru** [comment]
I don't think I will make any updates these days but I leave this implementation pending.

**Comment by wiruwiru** [comment]
Added in [NeedSystem v1.1.1](https://github.com/wiruwiru/NeedSystem-CS2/releases/tag/build-25). 
Thanks for the suggestion!
