### ISSUE TITLE
[REQ] Variable `{ServerName}` for webhook

### ISSUE THREAD

**Issue by crashzk** [wiruwiru/NeedSystem-CS2#8]
It would be possible to use the variable `{ServerName}` where it returns the hostname of the server.

I would like to implement it in the message sent on discord to have more information about the server.

**Comment by wiruwiru** [comment]
I don't think I'm going to make updates these days but I'm leaving this implementation pending, I'm thinking about adding it to the lang file.

**Comment by wiruwiru** [comment]
Added in [NeedSystem v1.1.2](https://github.com/wiruwiru/NeedSystem-CS2/releases/tag/build-26).

In this version I added the configuration option “UseHostname” to print the name you have configured in your server.cfg file. Hostname if set to true will be printed in “EmbedTitle”.

Thanks for the suggestion!
